### ISSUE TITLE
Can't connect to my bridge 2.0

### ISSUE THREAD

**Issue by SCZattix** [Blodjer/HueImmersive#15]
I push the button of the bridge like 5 times but the launcher stays loading, i think he can't find my bridge
(im on the same network)
 http://prntscr.com/a9jbmc

Or it stays like this: http://prntscr.com/a9jjtp
what can i do? :(
Thanks.

**Comment by polykoma** [comment]
Hey man i changed to bridge 2.0 for month now and everything works like with 1.0 

Must be a problem on your side.
Sorry to say

Try reset the bridge first!

**Comment by SCZattix** [comment]
It works perfect till i reset my pc :(
maybe i can try to reset my bridge 2.0

**Comment by polykoma** [comment]
Yes please try setup everything from zero (after reset of the bridge)

**Comment by Madejyalook** [comment]
I've also tried restarting my PC (Win10) and factory resetting my bridge 2.0. I also get stuck on the push-the-button screen.

**Comment by lachmans** [comment]
Hi all, does resetting your bridge 2.0 help with resolving the issue? I have, been unable to connect to my bridge 2.0.

**Comment by polykoma** [comment]
I have the 2.0 bridge since day 1

I had same issue but got it fixed with reseting and the first steps on the API.

everything works with 2.0 under win7 properly

**Comment by lachmans** [comment]
I've just resetted my bridge and redownloaded the HueImmersive app. To bad but it didn't fixed the issue. I'm still unable to connect to my bridge.

**Comment by bandedos** [comment]
I have the same problem. Other applications works OK.

**Comment by lachmans** [comment]
Hi there,

Thanks for replying. Are you planning on fixing it maybe? Because you would
help me out a lot and make me very, very happy!

Kind regards,
Roy

On Thursday, 2 June 2016, Damjan Kovač <notifications@github.com> wrote:

> I have the same problem. Other applications works OK.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Blodjer/HueImmersive/issues/15#issuecomment-223228439>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASuSaPqeqkuvtQ0CMIPhkPA3NDgggf8uks5qHpShgaJpZM4Hlwrk>
> .
>


-- 
Sent from Gmail Mobile

**Comment by robot2xl** [comment]
Use http://www.screenbloom.com/
